/*
CREATE DATABASE temcorte;

use temcorte;

SET time_zone = '-03:00';
# SELECT NOW();

*/
/*

CREATE TABLE IF NOT EXISTS state(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(10) NOT NULL,
     initials VARCHAR (2) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS city(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	 name VARCHAR(25) NOT NULL,
     initials VARCHAR (5) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_state INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_state) REFERENCES state(id)
);

CREATE TABLE IF NOT EXISTS address(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    street VARCHAR (25) NOT NULL,
    neighborhood VARCHAR (15) NOT NULL,
    num INT NOT NULL,
    cep VARCHAR(8) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME NULL,
    fk_city INT UNSIGNED NOT NULL,
    FOREIGN KEY  (fk_city) REFERENCES city(id)
);

CREATE TABLE IF NOT EXISTS social(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    facebook VARCHAR(15) NOT NULL DEFAULT 'facebook',
    instagram VARCHAR(15) NOT NULL DEFAULT 'instagram',
    whatsapp VARCHAR (14) NOT NULL DEFAULT '+0000000000000',
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS website(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(25) NOT NULL,
     description VARCHAR(100) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_address INT UNSIGNED DEFAULT 0,
     fk_social INT UNSIGNED DEFAULT 0,
	FOREIGN KEY  (fk_address) REFERENCES address(id),
    FOREIGN KEY  (fk_social) REFERENCES social(id)
);

CREATE TABLE IF NOT EXISTS user_level(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(15) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME DEFAULT NULL 
);

CREATE TABLE IF NOT EXISTS user(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(15) NOT NULL,
     surname VARCHAR(15) NOT NULL,
     email VARCHAR(45) NOT NULL,
     cpf VARCHAR(11) NOT NULL,
     password VARCHAR(32) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_level INT UNSIGNED NOT NULL,
     fk_address INT UNSIGNED DEFAULT 0,
     fk_social INT UNSIGNED DEFAULT 0,
     FOREIGN KEY (fk_level) REFERENCES user_level(id),
     FOREIGN KEY (fk_address) REFERENCES address(id),
     FOREIGN KEY (fk_social) REFERENCES social(id)
);

CREATE TABLE IF NOT EXISTS day(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(15) NOT NULL,
     initials VARCHAR (3) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME
);

CREATE TABLE IF NOT EXISTS day_active(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_employee INT UNSIGNED NOT NULL,
     fk_day INT UNSIGNED NOT NULL,
     fk_city INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_employee) REFERENCES user(id),
     FOREIGN KEY (fk_day) REFERENCES day(id),
     FOREIGN KEY (fk_city) REFERENCES city(id)
);

CREATE TABLE IF NOT EXISTS holiday(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(25) NOT NULL,
     date DATE NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_employee INT UNSIGNED NOT NULL,
     fk_city INT UNSIGNED NOT NULL,
	 FOREIGN KEY (fk_employee) REFERENCES user(id),
     FOREIGN KEY (fk_city) REFERENCES city(id)
);

CREATE TABLE IF NOT EXISTS time(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     time TIME NOT NULL,
	 created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS time_active(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_employee INT UNSIGNED NOT NULL,
     fk_time INT UNSIGNED NOT NULL,
     fk_city INT UNSIGNED NOT NULL,
     fk_day INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_employee) REFERENCES user(id),
     FOREIGN KEY (fk_time) REFERENCES time(id),
     FOREIGN KEY (fk_city) REFERENCES city(id),
     FOREIGN KEY (fk_day) REFERENCES day_active(id)
);

CREATE TABLE IF NOT EXISTS service(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(25) NOT NULL,
     duration TIME NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS service_active(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_service INT UNSIGNED NOT NULL,
     fk_city INT UNSIGNED NOT NULL,
     fk_employee INT UNSIGNED NOT NULL,
     fk_day INT UNSIGNED NOT NULL,
	 FOREIGN KEY (fk_service) REFERENCES service(id),
     FOREIGN KEY (fk_city) REFERENCES city(id),
     FOREIGN KEY (fk_employee) REFERENCES user(id),
     FOREIGN KEY (fk_day) REFERENCES day(id)
);

CREATE TABLE IF NOT EXISTS scheduling(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     start DATETIME NOT NULL,
     end DATETIME NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_service INT UNSIGNED NOT NULL,
     fk_client INT UNSIGNED NOT NULL,
     fk_employee INT UNSIGNED NOT NULL,
     fk_city INT UNSIGNED NOT NULL,
	 FOREIGN KEY (fk_service) REFERENCES service(id),
     FOREIGN KEY (fk_client) REFERENCES user(id),
     FOREIGN KEY (fk_employee) REFERENCES user(id),
     FOREIGN KEY (fk_city) REFERENCES city(id)
);
*/






## ANTIGO
/*
CREATE TABLE IF NOT EXISTS info(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
	phone VARCHAR (14) NOT NULL,
    neighborhood VARCHAR (9) NOT NULL,
    street VARCHAR (9) NOT NULL,
    num INT NOT NULL,
    cep VARCHAR(8) NOT NULL,
    facebook VARCHAR(15) NOT NULL DEFAULT 'facebook',
    instagram VARCHAR(15) NOT NULL DEFAULT 'instagram',
    whatsapp VARCHAR (14) NOT NULL DEFAULT '+0000000000000',
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS website(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(20) NOT NULL,
     description VARCHAR(100) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_info INT UNSIGNED NOT NULL,
	FOREIGN KEY  (fk_info) REFERENCES info(id)
);

CREATE TABLE IF NOT EXISTS user_level(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(15) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS user(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(25) NOT NULL,
     surname VARCHAR(25) NOT NULL,
     email VARCHAR(30) NOT NULL,
     password VARCHAR(32) NOT null,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_type INT UNSIGNED NOT NULL,
     fk_info INT UNSIGNED NOT NULL,
     FOREIGN KEY  (fk_type) REFERENCES user_level(id),
     FOREIGN KEY  (fk_info) REFERENCES info(id)
);

CREATE TABLE IF NOT EXISTS state(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(10) NOT NULL,
     initials VARCHAR (2) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS city(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	 name VARCHAR(25) NOT NULL,
     initials VARCHAR (5) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_state INT UNSIGNED NOT NULL,
     fk_info INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_state) REFERENCES state(id),
     FOREIGN KEY (fk_info) REFERENCES info(id)
);

CREATE TABLE IF NOT EXISTS employee(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified DATETIME NULL,
    fk_user INT UNSIGNED NOT NULL,
	FOREIGN KEY  (fk_user) REFERENCES user(id)
);


CREATE TABLE IF NOT EXISTS holiday(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(25) NOT NULL,
     date DATE NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
	 fk_city INT UNSIGNED NOT NULL,
     fk_employee INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_city) REFERENCES city(id),
	 FOREIGN KEY (fk_employee) REFERENCES employee(id)
);

CREATE TABLE IF NOT EXISTS day(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(15) NOT NULL,
     initials VARCHAR (3) NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS day_active(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_city INT UNSIGNED NOT NULL,
     fk_user INT UNSIGNED NOT NULL,
     fk_day INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_city) REFERENCES city(id),
     FOREIGN KEY (fk_user) REFERENCES user(id),
     FOREIGN KEY (fk_day) REFERENCES day(id)
);

CREATE TABLE IF NOT EXISTS time(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR (5) NOT NULL,
     value TIME NOT NULL,
	 created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS time_active(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_city INT UNSIGNED NOT NULL,
     fk_user INT UNSIGNED NOT NULL,
     fk_time INT UNSIGNED NOT NULL,
     fk_day INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_city) REFERENCES city(id),
     FOREIGN KEY (fk_user) REFERENCES user(id),
     FOREIGN KEY (fk_time) REFERENCES time(id),
     FOREIGN KEY (fk_day) REFERENCES day_active(id)
);

CREATE TABLE IF NOT EXISTS service(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(25) NOT NULL,
     time TIME NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modified DATETIME NULL,
     fk_city INT UNSIGNED NOT NULL,
     fk_user INT UNSIGNED NOT NULL,
     fk_day INT UNSIGNED NOT NULL,
     FOREIGN KEY (fk_city) REFERENCES city(id),
     FOREIGN KEY (fk_user) REFERENCES user(id),
     FOREIGN KEY (fk_day) REFERENCES day(id)
);

CREATE TABLE IF NOT EXISTS scheduling(
	 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     start DATETIME NOT NULL,
     end DATETIME NOT NULL,
     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modofied DATETIME NULL,
     fk_service INT UNSIGNED NOT NULL,
     fk_city INT UNSIGNED NOT NULL,
     fk_employee INT UNSIGNED NOT NULL,
     fk_user INT UNSIGNED NOT NULL,
	 FOREIGN KEY (fk_service) REFERENCES service(id),
     FOREIGN KEY (fk_city) REFERENCES city(id),
     FOREIGN KEY (fk_employee) REFERENCES employee(id),
     FOREIGN KEY (fk_user) REFERENCES user(id)
);
*/
 
 /* POVOANDO */
/*
INSERT INTO state(name,initials) VALUES ("Piauí","PI");

INSERT INTO info (email, phone, neighborhood, street, num, cep) VALUES
("admin@temcorte.com", "+5500000000000", "Junco", "R. Cícero Duarte", 905, "64607670");

INSERT INTO info (email, phone, neighborhood, street, num, cep) VALUES
("contato@temcorte.com", "+5500000000000", "Junco", "R. Cícero Duarte", 905, "64607670");

INSERT INTO city (name, initials, fk_state, fk_info) VALUES
("Picos", "PC", 1,1);
*/

